[workspace]
members = [
  "ucan",
  "ucan-key-support",
  "ucan-wasm"
]

# Speedup build on macOS
# See https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#splitting-debug-information
[profile.dev]
split-debuginfo = "unpacked"

[profile.release.package.ucan-wasm]
opt-level = "z"
