name: Spellcheck

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matheus23/md-spellcheck-action@v4.2.2
        with:
          files-to-check: "**/*.md"
          words-to-ignore-file: ".github/workflows/dictionary.txt"
